default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: kiTindr_development

test:
  <<: *default
  database: kiTindr_test
production:
  <<: *default
  database: kiTindr_production
  username: kiTindr
  password: <%= ENV['KITINDR_DATABASE_PASSWORD'] %>
